name=AutoPack
version=1.0.0
author=Aadruta PB <aadrutapb@gmail.com>
maintainer=Aadruta PB <aadrutapb@gmail.com>
sentence=A zero-leak dynamic string unpacker for 8-bit microcontrollers.
paragraph=AutoPack parses variable-length delimited strings in-place and unpacks them directly into native C-style arrays (int, float, byte, char, String) to completely prevent heap fragmentation on SRAM-constrained AVR boards.
category=Data Processing
url=https://github.com
architectures=avr,megaavr,*
includes=AutoPack.h
